# Generated by Django 5.2.2 on 2025-06-07 19:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('cor', models.CharField(default='#007bff', help_text='Cor em formato hex (ex: #007bff)', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SessaoTempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, help_text='Opcional: descrição do que foi feito')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='projects.projeto')),
            ],
            options={
                'ordering': ['-inicio'],
            },
        ),
    ]
