# Generated by Django 5.2.2 on 2025-07-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='dados_teste',
            field=models.BooleanField(default=False, help_text='Marca se este projeto foi criado como dados de teste'),
        ),
        migrations.AddField(
            model_name='sessaotempo',
            name='dados_teste',
            field=models.BooleanField(default=False, help_text='Marca se esta sessão foi criada como dados de teste'),
        ),
    ]
